### PR TITLE
Improve "name_to_initials"

### LINKED ISSUE #59: Manual search displays author and narrator names incorrectly
When doing a manual match, the search results incorectly display the author initials.
Example:
```
Recursion by Blake Crouch and narrated by Jon Lindstrom
```
Is displayed as
`"Recursion" by B.C.Crouch w/ J.L.Lindstrom`

Expected
`"Recursion" by B. Crouch w/ J. Lindstrom`

This is probably a straightforward fix, if a string split is done on `' '`, to isolate the surname from the given name/initials/etc., before doing the string manipulation to work on authors that use initials instead of a given name.  I may do a PR if I'm feeling ambitious, though Python isn't my normal comfort zone.

### PR DESCRIPTION
**Pull request by rabelux**
On my opinion the new version is a bit more pythonic and it fixes #59

### CODE REVIEW

**Comment by djdembeck** [comment]
I jumped the gun on this. There are syntax errors:

```
2022-09-06 15:20:41,735 (152488202808) :  CRITICAL (core:615) - Exception starting plug-in (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-914ddd2b3/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/core.py", line 608, in start
    self.sandbox.execute(self.init_code)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-914ddd2b3/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 256, in execute
    exec(code) in self.environment
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Audnexus.bundle/Contents/Code/__init__.py", line 8, in <module>
    from search_tools import AlbumSearchTool, ArtistSearchTool, ScoreTool
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-914ddd2b3/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 333, in __import__
    return mod.load_module(_name)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-914ddd2b3/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 44, in load_module
    module = RestrictedModule(name, path, sandbox)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-914ddd2b3/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/loader.py", line 20, in __init__
    code = sandbox._core.loader.load(filename, sandbox.policy.elevated_execution)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-914ddd2b3/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/loader.py", line 47, in load
    code = self.compile(str(source), str(uni(filename)), elevated)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-914ddd2b3/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/loader.py", line 52, in compile
    return RestrictedPython.compile_restricted(source, name, 'exec', elevated=elevated)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-914ddd2b3/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/RestrictedPython/RCompile.py", line 115, in compile_restricted
    gen.compile()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-914ddd2b3/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/RestrictedPython/RCompile.py", line 68, in compile
    tree = self._get_tree()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-914ddd2b3/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/RestrictedPython/RCompile.py", line 59, in _get_tree
    tree = self.parse()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-914ddd2b3/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/RestrictedPython/RCompile.py", line 56, in parse
    return niceParse(self.source, self.filename, self.mode)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-914ddd2b3/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/RestrictedPython/RCompile.py", line 38, in niceParse
    compile(source, filename, mode)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Audnexus.bundle/Contents/Code/search_tools.py", line 100
    initials = [f"{s[0]}." if s[1] != "." else s for s in name_parts[:-1]]
                         ^
SyntaxError: invalid syntax

```

**Comment by rabelux** [comment]
Could it be that plex doesn't support f-strings yet? I tried to google plex's Python version but couldn't get any results. Do you know anything about it?

**Comment by djdembeck** [comment]
F strings are a Python 3 feature and Plex only supports Python 2

**Comment by rabelux** [comment]
Sorry for inconvenience. I'll revert it back to `s[0] + '.' ` tomorrow unless you want to change it right away.

**Comment by djdembeck** [comment]
> Sorry for the inconvenience. I'll revert it back to `s[0] + '.' ` tomorrow unless you want to change it right away.

Take your time :) Just open a new PR when you are ready.

**Comment by djdembeck** [comment]
@rabelux just checking in to see if you ever got around to this.

**Comment by rabelux** [comment]
Thank you for the reminder, I'll commit in roughly 12 hrs.

**Pull request merged**
